db:
  password: password;
  username: root
  url: localhost
  poolSize: 10

#logging:
#  level:
#    root: fatal
#    com.soCompany.database.ConnectionPool: info
#  file:
#    name: by.socompany
#    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: unknown
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate